-- USERS TABLE
create table users (
   user_id    number
      generated by default as identity
   primary key, -- Auto-increment primary key
   name       varchar2(100) not null, -- Name column
   email      varchar2(100) not null unique, -- Unique email constraint
   password   varchar2(255) not null, -- Password column
   phone      varchar2(20), -- Phone column
   role       varchar2(20) default 'Customer' check ( role in ( 'Admin',
                                                          'Customer' ) ), -- Role with default and check constraint
   created_at timestamp default systimestamp, -- Default timestamp for creation
   updated_at timestamp default systimestamp -- Default timestamp for updates
);

-- ROOMS TABLE
create table rooms (
   room_id      number
      generated by default as identity
   primary key, -- Auto-increment primary key
   name         varchar2(100) not null, -- Name column
   description  varchar2(500), -- Room description
   price        number(10,2) not null, -- Room price
   availability number(1) default 1, -- Availability: 1 (true), 0 (false)
   image        varchar2(255), -- Image URL
   room_type    varchar2(50) -- Room type
);

-- FEATURED ROOMS TABLE
create table featured_rooms (
   featured_room_id number
      generated by default as identity
   primary key, -- Auto-increment primary key
   room_id          number not null
      references rooms ( room_id )
         on delete cascade -- Foreign key to rooms table
);

-- ACTIVITIES TABLE
create table activities (
   activity_id number
      generated by default as identity
   primary key, -- Auto-increment primary key
   name        varchar2(100) not null, -- Activity name
   description varchar2(500), -- Activity description
   price       number(10,2) not null, -- Activity price
   image       varchar2(255) -- Image URL
);

-- FEATURED ACTIVITIES TABLE
create table featured_activities (
   featured_activity_id number
      generated by default as identity
   primary key, -- Auto-increment primary key
   activity_id          number not null
      references activities ( activity_id )
         on delete cascade -- Foreign key to activities table
);

-- BOOKINGS TABLE
create table bookings (
   booking_id  number
      generated by default as identity
   primary key, -- Auto-increment primary key
   user_id     number not null
      references users ( user_id )
         on delete cascade, -- Foreign key to users table
   room_id     number not null
      references rooms ( room_id )
         on delete cascade, -- Foreign key to rooms table
   check_in    date not null, -- Check-in date
   check_out   date not null, -- Check-out date
   total_price number(10,2) not null -- Total price for the booking
);

-- REVIEWS TABLE
create table reviews (
   review_id   number
      generated by default as identity
   primary key, -- Auto-increment primary key
   user_id     number not null
      references users ( user_id )
         on delete cascade, -- Foreign key to users table
   room_id     number not null
      references rooms ( room_id )
         on delete cascade, -- Foreign key to rooms table
   rating      number(1) check ( rating between 1 and 5 ) not null, -- Rating between 1 and 5
   review_text varchar2(500), -- Review text
   review_date timestamp default systimestamp -- Review date
);

-- FEATURED REVIEWS TABLE
create table featured_reviews (
   featured_review_id number
      generated by default as identity
   primary key, -- Auto-increment primary key
   review_id          number not null
      references reviews ( review_id )
         on delete cascade -- Foreign key to reviews table
);

-- HOMEPAGE HEADER TABLE
create table homepage_header (
   header_id    number
      generated by default as identity
   primary key, -- Auto-increment primary key
   image        varchar2(255) not null, -- Header image URL
   overlay_text varchar2(255) -- Overlay text
);

-- RELATIONSHIPS AND INDEXES
-- Create index for bookings by user_id
create index idx_booking_user_id on
   bookings (
      user_id
   );

-- Create index for reviews by room_id
create index idx_review_room_id on
   reviews (
      room_id
   );

-- Create index for featured rooms by room_id
create index idx_featured_room_room_id on
   featured_rooms (
      room_id
   );

-- Create index for featured activities by activity_id
create index idx_featured_activity_activity_id on
   featured_activities (
      activity_id
   );

-- Create index for featured reviews by review_id
create index idx_featured_review_review_id on
   featured_reviews (
      review_id
   );

-- Create index for homepage header image
create index idx_homepage_header_image on
   homepage_header (
      image
   );